#!/bin/bash

# Show the most recently changed items in the folder
#
# NOTE: I know I should probably use a more portable shebang,
# but keep in mind:
# 1. This is a script for my personal use
# 2. PRs welcome if you really feel up for it

EXEC_NAME="$0"
usage() {
cat <<HELP
usage ${EXEC_NAME} [OPTION]... [TARGET]

List by use date.

If no location is not specified, the current working
directory is used. If you prefer to set defaults, you
can set LU_* variables in your shell profile which will
be used as default values.


TARGET:
    A directory to show the most recent items from. 

Optional flags:

    -h,  --help
        Show this message and exit.

    -n NUMBER, --number [0-9]+
        Show this many entries (defaults to all)

    -o, --order (new|old)
        Either "newest" or "oldest" at the bottom.

    -c (auto|never|always), --color (auto|never|always)
        Enable color output for the file listing.

    -g, --no-color
        Shorthand for --color=never.

HELP
}

error() {
    printf "ERROR: ${*}" 1>&2
}

LU_POSITINALS=()


shift
while [[ $# -gt 0 ]]; do
    case "$arg" in
        -h|--help)     show_help                 ; exit  0 ;;
        -n|--number)   LU_SHOW_LAST_NUMBER="$2"  ; shift 2 ;;
        -o|--order)    LU_ORDERING="$2"          ; shift 2 ;;
        -c|--color)    LU_COLOR_FLAG="$2"        ; shift 2 ;;
        -g|--no-color) LU_COLOR_FLAG=""          ; shift 1 ;;
        -*|--*)        error "Unknown option $1" ; exit  1 ;;
        *)             LU_POSITIONALS+=("$1")    ; shift 1 ;;
    esac
done

# Validate and set values if no 
if [ -z ${LU_SHOW_LAST_NUMBER+x} ]; then
    LU_SHOW_LAST_NUMBER=$(ls -1 | wc -l)
elif [[ $LU_SHOW_LAST_NUMBER -lt 0 ]]; then
    usage; exit 1;
fi
if [ -z ${LU_COLOR_FLAG+x} ]; then
    LU_COLOR_FLAG="auto" # Set automatic clor
else
    case "$LU_COLOR_FLAG" in
        auto);;
        always);;
        never);;
        *) error "invalid color value '${LU_COLOR_FLAG}'"; exit 1 ;;
    esac
fi
if [ -z ${LU_ORDERING+x} ]; then
    LU_ORDERING="new"
fi
# Convert the order ordering value int a flag.
case "$LU_ORDERING" in
    new) LU_ORDER_FLAG="-A" ;;
    old) LU_ORDER_FLAG="-a" ;;
    *)      error "invalid ordering value '${LU_ORDERING}'"; exit 1 ;;
esac

if [ -z ${LU_TARGET+x} ]; then
    LU_TARGET="$(pwd)"
fi


ls -h "-ltrc" "${LU_ORDER_FLAG}" "--color=${LU_COLOR_FLAG}" "${LU_TARGET}"\
    | tail -n "${LU_SHOW_LAST_NUMBER}"

